import Head from 'next/head'
import Image from 'next/image'
import '../styles/globals.css'
export default function Home() {
	return (
		<div>
			<Head>
				<title>User home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</div>
	)
}
